<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<VersionPrefix>1.0.0</VersionPrefix>
		<VersionSuffix></VersionSuffix>
	</PropertyGroup>

	<PropertyGroup>
		<PackageId>WSCT.GUI.GlobalPlatformLauncher</PackageId>
		<Description>Launcher of WSCT GUI configured with GlobalPlatform plugins.</Description>
		<ApplicationIcon></ApplicationIcon>
	</PropertyGroup>

	<PropertyGroup>
		<UseWindowsForms>true</UseWindowsForms>
		<Win32Resource />
		<StartupObject />
	</PropertyGroup>

	<ItemGroup>
		<None Remove="Stack.Channel.xml" />
		<None Remove="Stack.Context.xml" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="WSCT.GUI" />
		<PackageReference Include="WSCT.JCSimulator" />
		<PackageReference Include="WSCT.Plugin.ISO7816Tools" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\WSCT.GUI.Plugins.GlobalPlatform\WSCT.GUI.Plugins.GlobalPlatform.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="Stack.Channel.xml">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="Stack.Context.xml">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

</Project>